### ISSUE TITLE
charset and special characters.

### ISSUE THREAD

**Issue by SimonSJensen** [apihlaja/node-irsdk#1]
First of all, thanks for making this. 

But it seems that special chars like é, ä etc. are not encoded corretly in the sessioninfo. I get driver names with unreadable chars. I've backtracked the sessioninfo and the call to IrSdkWrapper.getSessionInfo() in JsIrSdk.js doesn't return a propper utf8 encoded yaml string.

**Comment by apihlaja** [comment]
I turned out session info is Latin1 encoded, I expected it to be UTF-8.
