### ISSUE TITLE
Telemetry update interval ignored for replays. 

### ISSUE THREAD

**Issue by yanongena** [apihlaja/node-irsdk#22]
I am trying to get info about current positions and deltas from a replay. 
I have this code running: 
`iracing.on('Telemetry', function (data) {
    console.log('got Telemetry')

    for(var i = 0;i<drivers.length;i++){
        var driver = drivers[i];
        //console.log(driver.UserName + " Num: " + driver.CarNumber + " Idx " + driver.CarIdx);
    }

    var tel = data.values;
    //console.log(tel);

    var carPositions = tel.CarIdxPosition;
    var delta = tel.CarIdxF2Time;

    for(var i =1;i<carPositions.length;i++){
        if(carPositions[i] != 0){
            var driver = drivers[carPositions[i]];
            console.log(driver.UserName + " Delta: " + delta[i-1]);
        }
    }
    console.log("----------------------------------------------------");
})`

The update interval is set to 1000 so every second it outputs the data however I notice it's always the same. 
Only when the leader crosses the line, the data is updated.

**Comment by apihlaja** [comment]
Output is not cached or anything like that. You are always getting "fresh" data and it's pretty much raw output from iRacing. The most likely issue is that replays don't provide full telemetry so many things may not work as expected.

Also, I don't see you using anything that's supposed to be updated more frequently than once per lap. `CarIdxF2Time` is gap to leader on S/F line. And `CarIdxPosition` updates at S/F too. If there is driver swap, then `UserName` should update immediately but that's not telemetry variable. `CarIdxEstTime` contains F3 blackbox data so it updates more frequently but maybe that doesnt work in replays at all.

**Comment by yanongena** [comment]
Ah right, I wasn't aware that CarIdxF2Time only updates once a lap. 
I know that tools like iRTVO manage to get the deltas from the replay as well as driver swaps so the data is there somewhere. 
I haven't used the EstTime yet but I will look at that and see if that gives me the details I need. 

I just need to correct driver position and deltas from the telemetry so if EstTime can give me that info, maybe with some additional logic, than I'm happy with that. 
Will have a look at it and come back.
