### ISSUE TITLE
Start Replays, Change Camera

### ISSUE THREAD

**Issue by OthmanAba** [apihlaja/node-irsdk#6]
Can you provide an example for sending commands such as initiating replays, changing the camera, etc?

**Comment by apihlaja** [comment]
Only data access ie. telemetry and session info are supported at the moment. But like I said somewhere, I'll add commands if asked so.. #soon

**Comment by OthmanAba** [comment]
Thanks, this might help https://github.com/kutu/pyirsdk/blob/master/irsdk.py#L332-L375

**Comment by apihlaja** [comment]
I did some experiments earlier. I was thinking I could just expose [broadcast API](https://github.com/apihlaja/node-irsdk/blob/master/src/cpp/irsdk/irsdk_defines.h#L419) with related enums but it began to look mess.

I'll try something similar to what @kutu did ie. provide bunch of helper functions to dodge most of enums.

**Comment by kutu** [comment]
![](https://static-cdn.jtvnw.net/emoticons/v1/81103/1.0)

**Comment by apihlaja** [comment]
Done & released... also: [cam-example.js](https://github.com/apihlaja/node-irsdk/blob/master/utils/cam-example.js) and new [API doc](https://apihlaja.github.io/node-irsdk/).
