### ISSUE TITLE
Latitude and Longitude in Telemetry events

### ISSUE THREAD

**Issue by JakeNeighbors** [apihlaja/node-irsdk#63]
I was looking though the telemetry event and noticed that latitude and longitude were not available. Is this because these values are not provided by iRacing themselves? Or is this value omitted from the exposed telemetry event? If these values cannot be included due to restrictions on iRacing's side, then are there any other type of coordinate systems that can be exposed?

I am aware that the current library/iRacing exposes the distance along the track since the starting line, but I am looking for something that provides a more detailed, raw, position of the vehicle.

**Comment by apihlaja** [comment]
Sorry, somehow I never actually replied for you. I'm not sure if GPS data is available directly. It used to be that iRacing didn't want to make it available. That might have changed, sample files in repo are 2 years old. Mu's documentation kind of suggests its there now: https://github.com/patrickmoore/Mu#gps

Even if coordinates arent available, iRacing telemetry itself is so accurate that you should be able to calculate coordinates as long as you work out one fixed point on S/F line.
