### ISSUE TITLE
Prebuild binaries

### ISSUE THREAD

**Issue by apihlaja** [apihlaja/node-irsdk#9]
I have been thinking about providing pre-build binaries. Without [prebuild-ci](https://www.npmjs.com/package/prebuild-ci), it would have been pretty complicated. And I found the module only yesterday. Apparently it have been there for 2 years. Doh.

Pre-build binaries would mean that `node-irsdk` can be used without `node-gyp`: no need to go thru [this](https://github.com/nodejs/node-gyp#installation) to get started. Much easier..

So, that's on todo-list now. I´ll work on it soon™.

Other thing holding back this, is to figure out Node.js ABI versioning..

**Comment by SkippyZA** [comment]
This is going to be a massive thing for me. I made the post on the iRacing SDK forum requesting this sort of feature. I'm currently abstracting this all behind a RX stream and using a websocket source. For distribution, I am planning on switching to this so the client only needs to worry about installing 1 piece of software.

:+1: will be watching this :)
