### ISSUE TITLE
[Question] is there a way to get incidents data ?

### ISSUE THREAD

**Issue by jean-philippe-bousselin** [apihlaja/node-irsdk#92]
Hi, 

First of all let me thank you for your awesome work, it's brilliant!

I have a question regarding incidents, is there a way to gather the number of incidents for each car?

Regards,

Jean-Philippe.

**Comment by gmourier** [comment]
Hi Jean-philippe,

You can find theses informations inside SessionInfo. At first sight, i'm seeing **CurDriverIncidentCount** and **TeamIncidentCount**. Check it out on this [session info sample file](https://github.com/apihlaja/node-irsdk/blob/master/sample-data/sessioninfo.json)
