### ISSUE TITLE
Issue installing with node 16.13.1

### ISSUE THREAD

**Issue by nvduran** [apihlaja/node-irsdk#98]
I'm a bit of a noob so this may be a basic question. I've been trying to get this installed, and I am unable to troubleshoot this warning when doing npm i node-irsdk

npm WARN install Usage of the `--dev` option is deprecated. Use `--include=dev` instead.
npm ERR! code 1
npm ERR! path C:\Users\Nick\Desktop\irtest\node_modules\node-irsdk
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c prebuild-install || node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@16.13.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.6 found at "C:\Users\Nick\AppData\Local\Programs\Python\Python39\python.exe"
npm ERR! gyp info find VS using VS2017 (15.9.28307.1759) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\Nick\AppData\Local\Programs\Python\Python39\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\Nick\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Nick\\Desktop\\irtest\\node_modules\\node-irsdk\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Nick\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\Nick\\AppData\\Local\\node-gyp\\Cache\\16.13.1\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\Nick\\AppData\\Local\\node-gyp\\Cache\\16.13.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\Nick\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\Nick\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.13.1\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\Nick\\Desktop\\irtest\\node_modules\\node-irsdk',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\Nick\\Desktop\\irtest\\node_modules\\node-irsdk\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Traceback (most recent call last):
npm ERR!   File "C:\Users\Nick\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 45, in <module>
npm ERR!     sys.exit(gyp.script_main())
npm ERR!   File "C:\Users\Nick\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 662, in script_mainnpm ERR!     return main(sys.argv[1:])
npm ERR!   File "C:\Users\Nick\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 654, in main       
npm ERR!     return gyp_main(args)
npm ERR!   File "C:\Users\Nick\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 621, in gyp_main   
npm ERR!     [generator, flat_list, targets, data] = Load(
npm ERR!   File "C:\Users\Nick\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 142, in Load       
npm ERR!     result = gyp.input.Load(
npm ERR!   File "C:\Users\Nick\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 3009, in Load
npm ERR!     LoadTargetBuildFile(
npm ERR!   File "C:\Users\Nick\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 400, in LoadTargetBuildFile
npm ERR!     build_file_data = LoadOneBuildFile(
npm ERR!   File "C:\Users\Nick\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 237, in LoadOneBuildFile
npm ERR!     build_file_data = eval(build_file_contents, {"__builtins__": {}}, None)
npm ERR!   File "binding.gyp", line 1
npm ERR!     \ufeff{
npm ERR!     ^
npm ERR! SyntaxError: invalid non-printable character U+FEFF
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Nick\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:259:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Nick\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Nick\Desktop\irtest\node_modules\node-irsdk
npm ERR! gyp ERR! node -v v16.13.1
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Nick\AppData\Local\npm-cache\_logs\2022-01-02T01_49_11_284Z-debug-0.log

Thank you for any insight!

**Comment by sabifa** [comment]
If you could solve your problem please comment the solution here. It will help others to troubleshoot similar problems :)

**Comment by oibaf06** [comment]
please, i'm having the same issue and i really can't figure out how to solve it... i think the problems are the node and node-gyp versions... i'm using node@17.4.0 and node-gyp@3.8.0 can someone share whitch is the right version to use?

this is the full build log:
[2022-02-02T14_35_48_944Z-debug-0.log](https://github.com/apihlaja/node-irsdk/files/7987458/2022-02-02T14_35_48_944Z-debug-0.log)

**Comment by sabifa** [comment]
@oibaf06 I am using node-gyp@7.0.0 and node@12.22.0

**Comment by oibaf06** [comment]
omg i can't beleve this worked i've almost given up on this project for this error... love you (and your branch) @sabifa <3
